name: Build LaTeX document

on:   
  push:
    branches: ["main"]
    paths: ["./report/**"] # This will trigger the workflow when anything in the 'report/' folder is modified

jobs:
  build_latex:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: ./report/
          compiler: pdflatex
          args: |
            -interaction=nonstopmode
            -halt-on-error
          extra_system_packages: texlive-bibtex-extra
      - name: Run BibTeX
        run: bibtex main.aux
        working-directory: ./report/
      - name: Recompile LaTeX document after BibTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: ./report/
          compiler: pdflatex
          args: |
            -interaction=nonstopmode
            -halt-on-error

      - name: Commit and Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add ./report/main.pdf
          git commit -m "Add compiled PDF"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/lorenzoliuzzo/NODE.git main